repo: 'banner'
canvasCourse: 'web-dev-3'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true
    outline: true
    has:
      - 'link[href*="fonts.googleapis.com"]'
      - ['link[href*="type.css"] + link[href*="main.css"]', 'The `type.css` file must come before the `main.css` file.']
      - 'img[class~="img-flex"]'
      - '.banner'
      - '.banner > .banner-content'
      - '.banner > img'
      - '.banner-content > div'
      - '.banner-content > div > h1'
      - '.banner-content > div > p'
    search:
      - 'Space & Time Explorer Person'
      - 'text-'
      - 'gutter-'
      - 'push-'
      - 'max-length|wrapper'
      - 'micro|milli|kilo|mega|giga|tera|peta|exa|zetta|yotta'

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['html', 'text-size-adjust', '100%']
      - ['html', '-moz-text-size-adjust', '100%']
      - ['html', '-ms-text-size-adjust', '100%']
      - ['html', '-webkit-text-size-adjust', '100%']
      - ['*', 'box-sizing', 'inherit']
    search:
      - '@-moz-viewport'
      - '@-ms-viewport'
      - '@-o-viewport'
      - '@-webkit-viewport'
      - '@viewport'
      - 'position: relative'
      - 'position: absolute'
      - 'bottom'
      - 'left'
      - 'width'
      - 'overflow: hidden'
      - 'max-height'
    search_not:
      - 'font-size'
      - 'margin'
      - 'padding'
      - 'line-height'
  - path: 'css/type.css'
    valid: true
    bestPractices: true
    search:
      - ['https://typografier.web-dev.tools/#0,100,1.3,1.067,0;38,110,1.4,1.125,1;60,120,1.5,1.125,1;90,130,1.5,1.125,1', 'The `type.css` should be generated with Typografier’s default settings']

screenshots:
  - path: 'index.html'
    sizes: [608, 960, 1440]
